third attempt
stepancar-web-programming/2023-fall-lab-portfolio-fiskovich-n.-a. pull request #3
Opened 2024-01-18 07:22 UTC by Omniabene

2024-01-19 05:51 UTC, stepancar commented on js/media.js
> +  const isPlaying = player.classList.contains('play');
Есть такая сущность - хром плагин - часто плагины модифицируют DOM. Если такое произойдет, то логика вашего плеера будет разрушена. Более надежно - не хранить состояние прямо в слое представления.

2024-01-19 05:59 UTC, stepancar commented on js/media.js
> +  const audioContext = new (window.AudioContext || window.webkitAudioContext)();
обычно код полифилинга отделают непосредственно логики приложения, для того чтобы логика не зависила от этих делалей и можно было легко удалить устаревший полифил

2024-01-19 06:07 UTC, stepancar commented on js/media.js
> +  drawVisualizer();
Обратите внимание что если оставить песню - requestAnumationFrame продолжить работать и раз в 16ms будет выполняиться код. Одна из причин, почему у нас садятся батарейки - потому что разработчики забывают уничтожить таймеры, подписки. Попробуйте решить эту проблему так как решил бы ее бекэндер.

2024-01-19 06:11 UTC, stepancar commented on media.html
> +         </div>
Обратите внимание на то, что ваши кнопки хоть и выглядят как кнопки, но на них не работает навигация с клавиатуры.

2024-01-19 06:12 UTC, stepancar commented on music/Котозависимый.mp3
прекрасно!

2024-01-19 06:16 UTC, stepancar requested changes
Оставил комментарии.

На защиту: Вашему питомцу просто необходима гугл аналитика или яндекс метрика или mixpanel чтобы точно знать сколько людей на него смотрело, какие песни люди включали послушать.

2024-01-21 14:05 UTC, Omniabene commented on js/media.js
> +  const isPlaying = player.classList.contains('play');
разделил функцию на несколько

2024-01-21 14:06 UTC, Omniabene commented on js/media.js
> +  const audioContext = new (window.AudioContext || window.webkitAudioContext)();
разделил функцию на несколько

2024-01-21 14:07 UTC, Omniabene commented on js/media.js
> +  const isPlaying = player.classList.contains('play');
модифицировал DOM

2024-01-21 14:07 UTC, Omniabene commented on media.html
> +         </div>
модифицировал DOM и подключил пробел и стралочки к плееру

2024-01-21 14:08 UTC, Omniabene commented on js/media.js
> +  drawVisualizer();
решил эту проблему, простым удалением AnimationFrame при завершении песни

2024-01-21 19:23 UTC, stepancar commented on js/media.js
> +    audioContext = new (window.AudioContext || window.webkitAudioContext)();
Как правило, полифилинг делается вне логики кода, чтобы было легко в какой-то момент его удалить.

2024-01-21 19:33 UTC, stepancar approved these changes
Из того, что было бы клево доделать чтобы можно было отправлять сайт членам вашей семьи. 
1) Стили хедера отличаются при переходе между страницами. Ощущение буд-то перешел на внешний сайт.
2) При переходе между страницами активный раздел не подчеркивается. Обычный паттерн навигации - выделять как-то текущий раздел, страницу
3) было бы круто иметь возможность прослушивать песни про кота и во время просмотра фотографий

2024-01-21 19:35 UTC, Omniabene commented
я так понимаю я могу заливать в main ветку?

2024-01-21 21:59 UTC, merged